FROM node as builder
WORKDIR /usr/src/app
COPY . /usr/src/app
RUN npm i --legacy-peer-deps && npm run build && rm -fr node_modules && npm i --production

FROM node:buster-slim
SHELL ["bash", "-c"]
WORKDIR /usr/src/app
ENV NODE_ENV=production
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update \
 && apt-get upgrade -y && apt-get install -y tzdata \
 && apt-get install -y lsb-release curl git vim sudo openssh-server tmux
RUN adduser --disabled-password --gecos "" buster \
 && echo buster:buster | chpasswd \
 && echo "buster ALL=(ALL:ALL) /usr/sbin/visudo" > /etc/sudoers.d/40-users
COPY --from=builder /usr/src/app/build /usr/src/app/build
COPY --from=builder /usr/src/app/node_modules /usr/src/app/node_modules
COPY package.json /usr/src/app
RUN rm -fr /var/lib/apt/lists/*
EXPOSE 3000
CMD ["bash", "-c", "/etc/init.d/ssh start && npm start"]
